[versions]
isPreview = "false" # true

# https://developer.android.com/studio/releases/build-tools.html#notes
buildTools = "36.1.0"
buildToolsPreview = "36.1.0"

minSdk = "23"

compileSdk = "36"
compileSdkMinor = "1"
compileSdkPreview = "CANARY"

compileSdkExtension = "19"

targetSdk = "36"
targetSdkPreview = "CANARY"

agp = "9.0.0"

activity = "1.12.3"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
core = "1.17.0"
webkit = "1.15.0"

kotlin = "2.3.10"

material = "1.13.0"

[libraries]
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
